name: Deploy to memflow registry

on: [push]

env:
  CARGO_TERM_COLOR: always

jobs:

  build_linux_x86_64:
    name: Build artifacts for ubuntu-latest (x86-64)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: cargo build --release --all-features
      - uses: actions/upload-artifact@v4
        with:
          name: library-ubuntu-x86-64
          path: target/release/*.so

  deploy_plugins:
    name: Deploy plugins
    runs-on: ubuntu-latest
    needs: [build_linux_x86_64]
    steps:
      - run: cargo install --git https://github.com/memflow/memflowup
      - run: echo "${{ secrets.MEMFLOW_REGISTRY_SIGNING_KEY}}" > ec-secp256k1-priv-key.pem

      - uses: actions/download-artifact@v4
        with:
          name: library-ubuntu-x86-64
      - run: memflowup --skip-version-check push --token ${{ secrets.MEMFLOW_REGISTRY_TOKEN }} --priv-key ec-secp256k1-priv-key.pem *.so
